### ISSUE TITLE
404 errors loading icons

### ISSUE THREAD

**Issue by jonnyshaw89** [ONSdigital/eq-survey-runner#1056]
### Expected behaviour
All icons should load and not generate 404 errors

### Actual behaviour
404 error is being generated while requesting icons
`"GET /s/img/icons/icons--check.svg%22 HTTP/1.1" 404`
`"GET /s/img/icons/icons--chevron-down.svg%22 HTTP/1.1" 404`

### Steps to reproduce the behaviour
Unknown

**Comment by davecharles** [comment]
The favicon 404's are generated when navigating to Launcher, not Runner.  The only other issue I'm seeing is (on a few androids I've tried including Galaxy S8:Chrome) is `Failed to set referrer policy` when navigating to runner.

I found [this](https://www.chromestatus.com/feature/5634117806850048) but that confuses me because this is not an issue on desktop Chrome.  Will take advice on raising a separate issue for it.
