### ISSUE TITLE
Validation error message validating from previous value/previous piped value is not as expected

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#1431]
### Expected behaviour
Must display a validation error:  Enter an answer less than or equal to £12.00.

On the summary page Total turn over was displayed as £1 but the piped values is displayed as £12

### Actual behaviour
Displaying a validation error: Enter an answer less than or equal to £1.00.

### Steps to reproduce the behaviour
Login into RRM
click on an RSI 0102 survey which is already in progress where all the questions are answered (not submitted)
In this case Total retail turnover: was £12
Try entering £13 as internet sales
Must trigger a validation error message saying 'Enter an answer less than or equal to £13.00.'

### Screenshot
<img width="780" alt="screen shot 2018-01-22 at 16 17 40" src="https://user-images.githubusercontent.com/21335236/35232001-38d9888a-ff92-11e7-873a-d602b8807165.png">
<img width="678" alt="screen shot 2018-01-22 at 16 33 59" src="https://user-images.githubusercontent.com/21335236/35232002-38f567d0-ff92-11e7-945b-7c161d851703.png">

**Comment by ajmaddaford** [comment]
We need to be able to reproduce this locally without using RRM. I've tried replicating it by getting a submission to the summary screen with the same details as above on v2.31.1 (the last release before today) and resuming it on v2.32.0 (todays release), but that worked as expected. When was the previous submission last touched before trying to resume it on v2.32.0?

**Comment by yoganandkunche** [comment]
@ajmaddaford submission was last touched during the smoke test of v2.30.0.

**Comment by jonnyshaw89** [comment]
@ajmaddaford should this still be open?

**Comment by ajmaddaford** [comment]
This was caused by old data on the answer store. It looks like an answer that had previously been provided was moved to another location. This meant that there were two answers for the same answer id in the answer store. 

The reason that different answers are displayed to the user is that validation (https://github.com/ONSdigital/eq-survey-runner/blob/master/app/forms/fields.py#L233) and summary values (https://github.com/ONSdigital/eq-survey-runner/blob/master/app/templating/summary/question.py#L26) take the first answer returned from the answer store filter method whereas piping (https://github.com/ONSdigital/eq-survey-runner/blob/master/app/templating/schema_context.py#L27) takes into consideration the routing path. 

While this isn't an issue that should affect respondents (as we don't move answers during collection periods), the application should be more resilient to this. We should discuss:
- Not allowing duplicate answer id's in the answer store (unless they are repeating)
- Should we error if there are multiple answers returned when we expect one?
- What can be done to rationalise getting answers from the answer store e.g. always considering if the answer is on the routing path.

**Comment by nealedj** [comment]
This occurred again recently with a test account. Although it manifested itself differently. A 500 was raised because `app.questionnaire.rules.get_answer_store_value` explicitly checks if there are multiple values are throws if so.

It seems that we're only experiencing this in test accounts that are holding onto very old data. I can't see how a duplicate answer would ever be able to get into the answer store now as the application only ever calls `AnswerStore.add_or_update` which will overwrite any existing value.

With that in mind, this seems like something that is unlikely affecting many/any real users.

Perhaps the solution therefore should be to make the code more resilient to this unlikely situation and just take the first result (because all overwrites of the answer will replace the first result).
