### ISSUE TITLE
Problems with navigation

### ISSUE THREAD

**Issue by LJBabbage** [ONSdigital/eq-survey-runner#331]
### Expected behaviour

The navigation should work throughout happy and unhappy paths
### Actual behaviour

This needs further testing to find all the problems, at present I am seeing state problems with the survey when using the back or forward buttons

**Comment by warrenbailey** [comment]
I'd suggest as part of this defect we increase the range of integration tests, as they are clearly lacking.

**Comment by warrenbailey** [comment]
Issues:
1. The back button doesn't work on first click - user remains on the same page
2. Clicking the back button twice results in previously entered data being lost

**Comment by LJBabbage** [comment]
On a multipage survey, if you get to the summary page and click back it takes you to the first page of the questionnaire not the last page as expected

**Comment by LJBabbage** [comment]
Further to the above if I now click save and continue, it takes me back to the summary page, it completely jumps the 2nd page

**Comment by warrenbailey** [comment]
This actually transpired to be two issue.

1] When jumping back through the survey the new user journey manager would archive the old pages before adjusting the current state of the list (as it should) however we weren't checking the archive for the old pages when returned to them. So they were being created fresh, hence why the data was lost. 
1. The templating pre-processor was being constructed as soon as a new request arrived and before the user journey manager had chance to do its thing. This meant it was actually rendering the previous template rather than the new one, which was the cause of the odd back button behaviour. 

Both have now been corrected.
