### ISSUE TITLE
Summary page has formatting issues

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#375]
### Expected behaviour
- Summary page should be formatted consistently, with no formatting issues.
### Actual behaviour

Summary page has formatting issues including:
- multiple selection/multiple answer (checkbox) responses use bullet points when only one answer has been provided.
- textarea responses that aren't the last response in that section are missing a separating line
- section titles aren't displayed
### Steps to reproduce the behaviour
- Complete Star Wars survey
- Verify formatting issues
### Screenshot

<img width="775" alt="screenshot 2016-08-12 15 20 55" src="https://cloud.githubusercontent.com/assets/930398/17625461/e39530e0-60a0-11e6-959f-de6aa9737b6c.png">

**Comment by collisdigital** [comment]
These will be fixed by https://trello.com/c/1At07GVd

**Comment by jjeane** [comment]
Additional issue - where label and title are both provided for a question (e.g. Jar Jar Bink's home planet) title is displayed in summary instead of label. 

<img width="742" alt="screen shot 2016-08-18 at 15 38 03" src="https://cloud.githubusercontent.com/assets/11901249/17777869/f8f5e9da-6559-11e6-8107-d49c2916b1f9.png">

**Comment by collisdigital** [comment]
@hamishtaplin is this resolved now?
