### ISSUE TITLE
Production database session errors

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#494]
[20161014-production-issue-stack-trace.txt](https://github.com/ONSdigital/eq-survey-runner/files/529841/20161014-production-issue-stack-trace.txt)

**Summary**
Reports of errors from survey runner users @ 14:45 on 14th October 2016. Logs showed one ec2 instance having errors with it's database session. Errors started @ 11:45. 

**Resolution**
The instance was terminated and elastic beanstalk started a new one. New instance did not have any issues connecting to the database.

**More information**
Repeating errors in the broken instance httpd error_log (stack trace attached)

**Comment by collisdigital** [comment]
Is this resolved by #556 or is more needed?

**Comment by benjefferies** [comment]
@collisdigital `sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.IntegrityError) duplicate key value violates unique constraint "questionnaire_state_pkey"` issue should be fixed by #556. However we would still get the integrity error as we did not implement any recovery changes as a part of the fix

**Comment by collisdigital** [comment]
But the instance recovers and the user can refresh the page and continue?

**Comment by benjefferies** [comment]
Yes, the instance will no longer get into a irrecoverable state when it has database session errors and the user will be able to continue.

**Comment by ajmaddaford** [comment]
Fixed in #556
