### ISSUE TITLE
Underscores in answer_ids cause submitter to fail

### ISSUE THREAD

**Issue by iwootten** [ONSdigital/eq-survey-runner#581]
### Expected behaviour

A schema that uses underscores within answer_ids in the survey json is able to have them submitted as per standard behaviour or a schema that uses underscores fails gracefully (or is unable to be selected?) upon validation.

### Actual behaviour

Submission fails with 'app.schema.exceptions.QuestionnaireException: Unknown id ' message.

### Steps to reproduce the behaviour

Create a survey using an answer_id with an underscore. Attempt to follow through the survey and submit.

### Technical information

This is failing because we use underscores to delimit between an answer_id and answer_instance when calling .map(). We should perhaps update the converter to use the answer_store, rather than the flattened list of answers. https://github.com/ONSdigital/eq-survey-runner/blob/master/app/submitter/converter.py#L87

**Comment by jonnyshaw89** [comment]
Can we enforce this on the schema validation?

**Comment by iwootten** [comment]
You mean as a test? Could do, depends what we think is most appropriate I guess.

**Comment by samiwel** [comment]
I think the issue here is that it's doing too simplistic a match on the instance Id and making an (incorrect) assumption that the instance id is whatever is to the right of the underscore. We fixed this in other places during the repeating single answer story for household composition - it looks like I missed this one. The converter should also be using the regular expression match to identify the answer instance Id correctly.

See PR for potential fix.
