### ISSUE TITLE
None or zero Visitors answer still shows Visitor section complete interstitial

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#740]
### Expected behaviour
- Visitors complete interstitial only shown when there are more than 0 visitors.

### Actual behaviour
- Visitors complete interstitial is shown even when there are 0 visitors or skipping forward and not answering the number of visitors question.

### Steps to reproduce the behaviour
- Start household questionnaire
- Skip the Household and Accommodation via navigation
- Complete Household and Accommodation section
- Observe that the Visitors complete interstitial is shown incorrectly.

#### Browser
Chrome

#### Operating System
macOS

### Screenshot
N/A

**Comment by benjefferies** [comment]
Because the interstitial page lives outside of the vistors repeating group it will always hit the 'You have now completed the visitors section' interstitial page. We don't support a binary repeat rule where you will either not repeat or show once so we cannot solve this problem in the same way the repeating of the visitors section is skipped.

After discussing with @ajmaddaford the possible options are:
1. Implement a repeat rule which will only show the visitors completed group once when overnight visitors answer is 1 or more or not at all when overnight visitors answer is 0.
2. Implement skip conditions at the group level so that the visitors sections is skipped when overnight visitors is set to 0

Option 2 seems like it makes sense since that we are simply trying to skip a group

**Comment by collisdigital** [comment]
This still occurs if on the first page you jump straight the "Household and Accommodation" section and start filling it in; at the end you see the visitors complete interstitial then are routed back to the Who Lives Here? I'm marking this as P4 as it's not the most likely usage scenario and doesn't break anything.

**Comment by collisdigital** [comment]
Hmm raising this to a P3 as if you do skip Who Lives Here? then go back and enter >0 visitors the visitor section appears as completed in the navigation (presumably because you've been through the visitors complete interstitial already).

**Comment by collisdigital** [comment]
Actually the same thing occurs if you change the number of visitors; but that really is a P4 (or 5 if we had it!)

**Comment by collisdigital** [comment]
Similar for going back and changing your household composition (adding people) if the group was previously completed it still gets a green tick, think we'll accept that behaviour for now.
