### ISSUE TITLE
When I change my route all answers are being submitted

### ISSUE THREAD

**Issue by LJBabbage** [ONSdigital/eq-survey-runner#858]
### Expected behaviour
When I change my route after answering a question (i.e go back and choose a different route) the submitter should not send any of the old routes data.
### Actual behaviour
All data is being sent regardless of the route
### Steps to reproduce the behaviour
1. Expose the message sent by the submitter, a simple logger message in send_answers will do it
2. Using test_conditional_routing, select Yes for the first question, fill out the next question so you are on the summary, now go back to the first question and change your answer to no i prefer tea, complete the survey, see that both responses for the 2nd questions are being passed

**Comment by samiwel** [comment]
As pointed out by @LJBabbage, the issue here lies in the data version of the test schema.
The `test_conditional_routing` schema has a data version of `0.0.1`. There is some conditional logic In `converter.py:60` that behaves differently depending on the data version of the schema.
Version `0.0.1` converts the data for the entire questionnaire.
Version `0.0.2` converts the data for the supplied routing path.
In this case, simply changing the data version to `0.0.2` resolves the issue.

**Comment by collisdigital** [comment]
Except UKIS uses version 0.0.1 so this needs fixing for that version as well until we upgrade all surveys to 0.0.2

**Comment by samiwel** [comment]
After further discussion and investigation, it seems that simply changing data version of the schema is not sufficient as there are differences in the way that the data is represented. Version `0.0.1` returns a dictionary of qcode -> value whereas version `0.0.2` returns a list of answers from the answer store. So some work will be required to use the routing path when extracting the data for surveys on data version `0.0.1`.
