### ISSUE TITLE
Using 'Enter' key on Household Composition removes people

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#859]
### Expected behaviour
- People aren't removed when hitting enter

### Actual behaviour
- People are removed
- Behaviour is inconsistent, sometimes Person 2 is removed regardless of who is being edited
- Sometimes hitting enter submits the form

### Steps to reproduce the behaviour
- Add a load of people
- Select Person 4's last name and hit enter, see who gets removed
- Select a different person and different field, see what happens
- Save and Continue and then go back
- Form behaves differently now that people are pre-rendered (not JS created).

#### Browser
Chrome

#### Operating System
macOS Sierra

### Screenshot
N/A

**Comment by collisdigital** [comment]
@hamishtaplin found that the remove link has a submit action on it when rendered by the backend, that should be removed. That may not solve all the quirks when hitting enter on these input fields though.

**Comment by samiwel** [comment]
At the moment the remove person links are just submit buttons in disguise. It was done this way to get the household composition screen to work before the Javascript enhanced implementation. My understanding is that when you hit the Enter key, it's always the first submit action on the form which gets invoked. So I think this is always Person 2 (since the first person is not able to be removed). I did not find a way to override this behaviour.

**Comment by collisdigital** [comment]
Possibly JS can remove the submit actions for progressive enhancement @hamishtaplin ?

**Comment by samiwel** [comment]
Might be possible to do something like this: http://stackoverflow.com/a/1563238 but without JQuery and simulate a click on the Save and Continue rather than simulating a tab. I will pick this up and give it a try.
